        <script type="text/javascript" src="PERCH_LOGINPATH/addons/plugins/editors/markitup/jquery.markitup.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/addons/plugins/editors/markitup/settings.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/addons/plugins/editors/markitup/image_upload/image_upload.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/core/assets/js/jquery.form.min.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/addons/plugins/editors/markitup/config.js"></script>
        <link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/markitup/skin.css" type="text/css" />
        <link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/markitup/style.css" type="text/css" />
        <link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/markitup/image_upload/image_upload.css" type="text/css" />

